// import './example/basic-type'
// import './example/symbol'
// import './example/interface'
// import './example/function'
// import './example/class'
// import './example/generic'
// import './example/enum'
import './example/Intersection'